// Shared test-support — SdkPublicApiSignature (S08-F-02 / M4 follow-up).
//
// The ONE canonical public-API signature builder shared by every golden-snapshot
// freeze gate (SdkContractFreezeTests over Platform.Sdk; SdkTestingContractFreezeTests
// over Platform.Sdk.Testing).  Extracted verbatim from the original copy that lived
// inside tests/Platform.Sdk.Tests/SdkContractFreezeTests.cs so that both goldens are
// emitted by an IDENTICAL canonicalisation and are therefore byte-comparable.  Only
// the namespace and the access modifier changed in the move (internal → public, so a
// sibling test assembly can call it); the Build(...) output is unchanged.
//
// Canonicalization / inclusion rule (mirror this when regenerating a golden):
//   • Types: every public type in the assembly (IsPublic || IsNestedPublic),
//     sorted by full reflection name ordinally.  Each type emits a "kind" header
//     (interface / record / class / struct / enum / delegate) + its generic
//     parameters + its declared base type and directly-implemented interfaces.
//   • Members: only members DECLARED on the type (BindingFlags.DeclaredOnly), public
//     instance + static, sorted ordinally by a stable per-member signature string.
//   • EXCLUDED as compiler-generated noise (a record's synthesised surface adds no
//     contract information and its formatting is unstable across SDKs):
//       - anything marked [CompilerGenerated],
//       - the record value-equality / copy surface:
//         EqualityContract, <Clone>$, Equals(object), Equals(<self>),
//         GetHashCode, ToString, PrintMembers, Deconstruct,
//         op_Equality, op_Inequality, and the copy-constructor (T(T)).
//     The positional record PROPERTIES and any author-declared members survive —
//     those ARE the contract.  Enum members are emitted as named constants.
//   • Type names are formatted by a single deterministic formatter (FormatType):
//     generic type parameters render by their own name (TModel), constructed
//     generics render as Name<Arg,Arg>, arrays/byref/nullable-annotations are
//     handled uniformly.  Never rely on reflection member ORDER (it is unstable);
//     everything is sorted with StringComparer.Ordinal / string.CompareOrdinal.
using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Text;

namespace Platform.TestSupport;

/// <summary>
/// Builds the canonical, deterministic text signature of a public assembly
/// surface used by every contract-freeze gate.  See the inclusion rule documented
/// at the top of this file (and mirrored in the gates that consume it).
/// </summary>
public static class SdkPublicApiSignature
{
    // Record / value-equality synthesised members that carry no contract
    // information and whose formatting is unstable across SDKs.  Excluded by name.
    private static readonly HashSet<string> s_syntheticMemberNames = new(StringComparer.Ordinal)
    {
        "EqualityContract",
        "<Clone>$",
        "PrintMembers",
        "Deconstruct",
        "op_Equality",
        "op_Inequality",
        "GetHashCode",
        "ToString",
    };

    /// <summary>
    /// Reflects over every public type in <paramref name="assembly"/> and returns
    /// a deterministic, newline-joined signature of the whole public surface.
    /// </summary>
    public static string Build(Assembly assembly)
    {
        var types = assembly.GetTypes()
            .Where(t => t.IsPublic || t.IsNestedPublic)
            .OrderBy(t => t.FullName ?? t.Name, StringComparer.Ordinal)
            .ToList();

        var sb = new StringBuilder();
        sb.Append("# Platform.Sdk v1 provider contract — FROZEN for the v1.x engine series.\n");
        sb.Append("# Generated by the shared SdkPublicApiSignature canonicaliser; do not hand-edit. v1.x is additive-only — regenerate via the freeze test and review, or revert.\n");

        foreach (var type in types)
        {
            AppendType(sb, type);
        }

        return sb.ToString();
    }

    private static void AppendType(StringBuilder sb, Type type)
    {
        sb.Append('\n');
        sb.Append(FormatTypeHeader(type));
        sb.Append('\n');

        if (type.IsEnum)
        {
            foreach (var line in EnumMemberLines(type))
            {
                sb.Append("  ");
                sb.Append(line);
                sb.Append('\n');
            }

            return;
        }

        foreach (var line in MemberLines(type))
        {
            sb.Append("  ");
            sb.Append(line);
            sb.Append('\n');
        }
    }

    // ── Type header ──────────────────────────────────────────────────────────

    private static string FormatTypeHeader(Type type)
    {
        var kind = TypeKind(type);
        var name = FormatType(type);

        // Declared, directly-implemented interfaces + base type, sorted ordinally,
        // so the header captures the type's contract relationships deterministically.
        var supertypes = new List<string>();

        if (type.BaseType is not null
            && type.BaseType != typeof(object)
            && type.BaseType != typeof(ValueType)
            && type.BaseType != typeof(Enum))
        {
            supertypes.Add(FormatType(type.BaseType));
        }

        foreach (var iface in DirectlyImplementedInterfaces(type))
        {
            supertypes.Add(FormatType(iface));
        }

        supertypes.Sort(StringComparer.Ordinal);

        var header = supertypes.Count == 0
            ? $"{kind} {name}"
            : $"{kind} {name} : {string.Join(", ", supertypes)}";

        return header;
    }

    private static string TypeKind(Type type)
    {
        if (type.IsEnum)
        {
            return "enum";
        }

        if (type.IsInterface)
        {
            return "interface";
        }

        if (typeof(Delegate).IsAssignableFrom(type))
        {
            return "delegate";
        }

        if (type.IsValueType)
        {
            return IsRecord(type) ? "record struct" : "struct";
        }

        return IsRecord(type) ? "record" : "class";
    }

    // A record is identified structurally by its compiler-synthesised
    // EqualityContract property (classes/structs do not have it).
    private static bool IsRecord(Type type) =>
        type.GetProperty(
            "EqualityContract",
            BindingFlags.Instance | BindingFlags.NonPublic | BindingFlags.Public) is not null;

    // Only the interfaces this type DECLARES directly (not those inherited via a
    // base type or via another interface), so the header is stable and minimal.
    private static IEnumerable<Type> DirectlyImplementedInterfaces(Type type)
    {
        var all = type.GetInterfaces().ToHashSet();
        var inherited = new HashSet<Type>();

        if (type.BaseType is not null)
        {
            foreach (var i in type.BaseType.GetInterfaces())
            {
                inherited.Add(i);
            }
        }

        foreach (var i in all)
        {
            foreach (var nested in i.GetInterfaces())
            {
                inherited.Add(nested);
            }
        }

        return all.Where(i => !inherited.Contains(i) && (i.IsPublic || i.IsNestedPublic));
    }

    // ── Members ──────────────────────────────────────────────────────────────

    private static List<string> MemberLines(Type type)
    {
        const BindingFlags flags =
            BindingFlags.Public
            | BindingFlags.Instance
            | BindingFlags.Static
            | BindingFlags.DeclaredOnly;

        var lines = new List<string>();

        foreach (var ctor in type.GetConstructors(flags))
        {
            if (IsExcluded(ctor) || IsCopyConstructor(type, ctor))
            {
                continue;
            }

            lines.Add($".ctor({FormatParameters(ctor.GetParameters())})");
        }

        foreach (var prop in type.GetProperties(flags))
        {
            if (IsExcluded(prop))
            {
                continue;
            }

            var accessors = new List<string>();
            if (prop.GetMethod is { IsPublic: true })
            {
                accessors.Add("get");
            }

            if (prop.SetMethod is { IsPublic: true })
            {
                accessors.Add(IsInitOnly(prop.SetMethod) ? "init" : "set");
            }

            var indexerParams = prop.GetIndexParameters();
            var nameAndIndex = indexerParams.Length == 0
                ? prop.Name
                : $"{prop.Name}[{FormatParameters(indexerParams)}]";

            lines.Add(
                $"property {FormatType(prop.PropertyType)} {nameAndIndex} {{ {string.Join("; ", accessors)} }}");
        }

        foreach (var field in type.GetFields(flags))
        {
            if (IsExcluded(field))
            {
                continue;
            }

            var modifier = field.IsLiteral ? "const " : field.IsStatic ? "static " : string.Empty;
            lines.Add($"field {modifier}{FormatType(field.FieldType)} {field.Name}");
        }

        foreach (var method in type.GetMethods(flags))
        {
            if (method.IsSpecialName || IsExcluded(method) || s_syntheticMemberNames.Contains(method.Name))
            {
                continue;
            }

            var staticMod = method.IsStatic ? "static " : string.Empty;
            var generics = method.IsGenericMethodDefinition
                ? $"<{string.Join(",", method.GetGenericArguments().Select(a => a.Name))}>"
                : string.Empty;

            lines.Add(
                $"method {staticMod}{FormatType(method.ReturnType)} {method.Name}{generics}"
                + $"({FormatParameters(method.GetParameters())})");
        }

        lines.Sort(StringComparer.Ordinal);
        return lines;
    }

    private static List<string> EnumMemberLines(Type type)
    {
        var names = Enum.GetNames(type).ToList();
        names.Sort(StringComparer.Ordinal);
        return names.Select(n => $"enum-member {n}").ToList();
    }

    // ── Exclusion of compiler-generated / synthetic surface ──────────────────

    private static bool IsExcluded(MemberInfo member)
    {
        if (s_syntheticMemberNames.Contains(member.Name))
        {
            return true;
        }

        return member.GetCustomAttribute<CompilerGeneratedAttribute>() is not null
            && member is not PropertyInfo; // positional record properties carry [CompilerGenerated] but ARE the contract
    }

    // The record copy-constructor — a single parameter of the declaring type.
    private static bool IsCopyConstructor(Type type, ConstructorInfo ctor)
    {
        var ps = ctor.GetParameters();
        return ps.Length == 1 && ps[0].ParameterType == type;
    }

    private static bool IsInitOnly(MethodInfo setter) =>
        setter.ReturnParameter
            .GetRequiredCustomModifiers()
            .Any(m => m.FullName == "System.Runtime.CompilerServices.IsExternalInit");

    // ── Deterministic type-name formatter ────────────────────────────────────

    private static string FormatParameters(ParameterInfo[] parameters) =>
        string.Join(
            ", ",
            parameters.Select(p =>
            {
                var prefix = p.ParameterType.IsByRef
                    ? (p.IsOut ? "out " : p.IsIn ? "in " : "ref ")
                    : string.Empty;
                return $"{prefix}{FormatType(p.ParameterType)} {p.Name}";
            }));

    private static string FormatType(Type type)
    {
        if (type.IsByRef)
        {
            return FormatType(type.GetElementType()!);
        }

        if (type.IsArray)
        {
            var rank = type.GetArrayRank();
            var commas = rank > 1 ? new string(',', rank - 1) : string.Empty;
            return $"{FormatType(type.GetElementType()!)}[{commas}]";
        }

        if (type.IsGenericParameter)
        {
            return type.Name;
        }

        if (type.IsGenericType)
        {
            var def = type.GetGenericTypeDefinition();
            var baseName = StripArity(def.FullName ?? def.Name);
            var args = type.GetGenericArguments().Select(FormatType);
            return $"{baseName}<{string.Join(",", args)}>";
        }

        return type.FullName ?? type.Name;
    }

    private static string StripArity(string name)
    {
        var tick = name.IndexOf('`', StringComparison.Ordinal);
        return tick < 0 ? name : name[..tick];
    }
}
