// S10-E-02 (the auto-generated part) — the LANGUAGE REFERENCE generator.
//
// Produces a human-readable Markdown reference of every vouchfx step type
// DIRECTLY from the composed v1 JSON Schema (the same byte-stable JSON the
// SchemaComposer emits and the freeze gate snapshots).  Because the reference is
// generated from the schema rather than hand-maintained, it can never advertise a
// field the compiler does not accept, nor omit one it does — and the accompanying
// golden gate (LanguageReferenceGoldenTests) makes any drift a deliberate,
// reviewed act.
//
// WHERE THIS LIVES, AND WHY:
//   This generator lives in the TEST project, not the engine assembly.  It is a
//   pure documentation tool that consumes a composed-schema JSON STRING and returns
//   a Markdown STRING — it ships nothing at runtime and adds ZERO public engine
//   contract, so it cannot perturb any freeze gate (SdkContractFreezeTests, the
//   schema/event goldens, or the engine public-API surface).  It sits beside its
//   golden gate, exactly as the schema goldens sit beside SchemaFreezeTests.
//
// PURITY / DETERMINISM:
//   Generate(string) is a pure function of its input JSON.  Step-type sections are
//   sorted by step-type id (ordinal); within each section the required and optional
//   fields are each sorted by field name (ordinal).  The common step fields are
//   rendered once, in a fixed canonical order.  The output is therefore
//   byte-reproducible for a given composed schema.
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text;
using System.Text.Json;

namespace Vouchfx.Engine.Compilation.Tests;

/// <summary>
/// Generates the Markdown language reference (<c>docs/language-reference.md</c>)
/// from the composed v1 JSON Schema.  Pure and deterministic: the same composed
/// schema text always yields byte-identical Markdown.
/// </summary>
internal static class LanguageReferenceGenerator
{
    /// <summary>
    /// The fixed, canonical order in which the common step fields are documented.
    /// These are the fields the root schema declares on <c>$defs/step</c> that
    /// apply to <em>every</em> step regardless of its type.  A fixed order (rather
    /// than schema order) keeps the rendered "common fields" table stable even if
    /// the root schema's property order is ever reshuffled.
    /// </summary>
    private static readonly string[] CommonFieldOrder =
    {
        "id",
        "type",
        "description",
        "capture",
        "verifyMode",
        "timeout",
        "continueOnFailure",
    };

    /// <summary>
    /// Generates the complete Markdown language reference from a composed-schema
    /// JSON string (as produced by
    /// <see cref="Vouchfx.Engine.Compilation.Schema.SchemaComposer.ComposeSchemaJson"/>).
    /// </summary>
    /// <param name="composedSchemaJson">
    /// The composed v1 schema as canonical JSON text.
    /// </param>
    /// <returns>The language reference as a Markdown document (LF line endings).</returns>
    /// <exception cref="ArgumentException">
    /// Thrown when <paramref name="composedSchemaJson"/> is null or whitespace.
    /// </exception>
    /// <exception cref="InvalidOperationException">
    /// Thrown when the JSON does not have the expected composed-schema shape
    /// (missing <c>$defs/step</c>, etc.).
    /// </exception>
    public static string Generate(string composedSchemaJson)
    {
        if (string.IsNullOrWhiteSpace(composedSchemaJson))
            throw new ArgumentException("Composed schema JSON must not be null or whitespace.", nameof(composedSchemaJson));

        using var doc = JsonDocument.Parse(composedSchemaJson);
        var root = doc.RootElement;

        var schemaVersion = TryGetString(root, "x-vouchfx-schema-version") ?? "v1";

        var step = NavigateStepDefinition(root);

        var sb = new StringBuilder();

        WriteHeader(sb, root, schemaVersion);
        WriteCommonFields(sb, step);
        WriteStepTypes(sb, step);
        WriteFooter(sb);

        // Normalise to LF so the generated bytes are independent of the host OS;
        // the golden gate compares LF-normalised content.
        return sb.ToString().Replace("\r\n", "\n").Replace("\r", "\n");
    }

    // ── Document sections ──────────────────────────────────────────────────────

    private static void WriteHeader(StringBuilder sb, JsonElement root, string schemaVersion)
    {
        sb.Append("# vouchfx Language Reference\n\n");
        sb.Append("> **Generated file — do not edit by hand.**\n");
        sb.Append("> This reference is generated from the composed `")
          .Append(schemaVersion)
          .Append("` JSON Schema (the exact contract the compiler validates against),\n");
        sb.Append("> so it can never drift from what vouchfx actually accepts. See *Regenerating this file* at the foot of this document.\n\n");

        var title = TryGetString(root, "title");
        var description = TryGetString(root, "description");

        if (!string.IsNullOrEmpty(description))
        {
            sb.Append(EscapeInline(description!)).Append("\n\n");
        }
        else if (!string.IsNullOrEmpty(title))
        {
            sb.Append(EscapeInline(title!)).Append("\n\n");
        }

        sb.Append("Each test step is a typed action or assertion. Every step shares a set of **common fields** ");
        sb.Append("(documented first), plus the **type-specific fields** of its `type` discriminator ");
        sb.Append("(the `<family>.<provider>` value, e.g. `http.rest` or `db-assert.postgres`). ");
        sb.Append("The sections below list, for each step type, its required and optional fields with their types and descriptions.\n\n");

        sb.Append("**Schema version:** `").Append(schemaVersion).Append("`\n\n");
    }

    private static void WriteCommonFields(StringBuilder sb, JsonElement step)
    {
        sb.Append("## Common step fields\n\n");
        sb.Append("These fields may appear on **any** step, regardless of its `type`. ");
        sb.Append("`id` and `type` are required on every step; the rest are optional.\n\n");

        if (!step.TryGetProperty("properties", out var properties) ||
            properties.ValueKind != JsonValueKind.Object)
        {
            sb.Append("_(The root schema declares no common step properties.)_\n\n");
            return;
        }

        var required = ReadRequiredSet(step);

        sb.Append("| Field | Required | Type | Description |\n");
        sb.Append("| --- | --- | --- | --- |\n");

        foreach (var name in CommonFieldOrder)
        {
            if (!properties.TryGetProperty(name, out var field))
                continue;

            WriteFieldRow(sb, name, field, required.Contains(name));
        }

        sb.Append('\n');
    }

    private static void WriteStepTypes(StringBuilder sb, JsonElement step)
    {
        sb.Append("## Step types\n\n");

        var stepTypes = ReadStepTypes(step);

        if (stepTypes.Count == 0)
        {
            sb.Append("_(No step types are registered in this schema.)_\n\n");
            return;
        }

        // Stable ordering: sort step types by their id (ordinal).
        stepTypes.Sort(static (a, b) => string.CompareOrdinal(a.TypeId, b.TypeId));

        // A short index so a reader can jump to a step type.
        sb.Append("Registered step types (").Append(stepTypes.Count.ToString(CultureInfo.InvariantCulture)).Append("):\n\n");
        foreach (var st in stepTypes)
        {
            sb.Append("- [`").Append(st.TypeId).Append("`](#").Append(Anchor(st.TypeId)).Append(")\n");
        }

        sb.Append('\n');

        foreach (var st in stepTypes)
        {
            WriteStepTypeSection(sb, st);
        }
    }

    private static void WriteStepTypeSection(StringBuilder sb, StepType st)
    {
        sb.Append("### `").Append(st.TypeId).Append("`\n\n");

        if (!string.IsNullOrEmpty(st.Description))
        {
            sb.Append(EscapeInline(st.Description!)).Append("\n\n");
        }

        sb.Append("Set `type: ").Append(st.TypeId).Append("` to use this step.\n\n");

        var requiredFields = st.Fields
            .Where(f => st.Required.Contains(f.Name))
            .OrderBy(f => f.Name, StringComparer.Ordinal)
            .ToList();

        var optionalFields = st.Fields
            .Where(f => !st.Required.Contains(f.Name))
            .OrderBy(f => f.Name, StringComparer.Ordinal)
            .ToList();

        if (requiredFields.Count == 0 && optionalFields.Count == 0)
        {
            sb.Append("This step type declares no type-specific fields beyond the common fields.\n\n");
            return;
        }

        if (requiredFields.Count > 0)
        {
            sb.Append("**Required fields**\n\n");
            sb.Append("| Field | Type | Description |\n");
            sb.Append("| --- | --- | --- |\n");
            foreach (var f in requiredFields)
            {
                WriteTypeFieldRow(sb, f);
            }
            sb.Append('\n');
        }

        if (optionalFields.Count > 0)
        {
            sb.Append("**Optional fields**\n\n");
            sb.Append("| Field | Type | Description |\n");
            sb.Append("| --- | --- | --- |\n");
            foreach (var f in optionalFields)
            {
                WriteTypeFieldRow(sb, f);
            }
            sb.Append('\n');
        }
    }

    private static void WriteFooter(StringBuilder sb)
    {
        sb.Append("## Regenerating this file\n\n");
        sb.Append("This file is generated from the composed JSON Schema by ");
        sb.Append("`LanguageReferenceGenerator.Generate(...)` and frozen by the ");
        sb.Append("`LanguageReferenceGoldenTests` golden gate. When the schema legitimately changes ");
        sb.Append("(a provider adds an optional field, say), regenerate this file rather than editing it by hand:\n\n");
        sb.Append("```bash\n");
        sb.Append("# 1. Run the golden gate; on drift it prints the first differing line.\n");
        sb.Append("dotnet test tests/Vouchfx.Engine.Compilation.Tests \\\n");
        sb.Append("  --filter \"FullyQualifiedName~LanguageReferenceGoldenTests\"\n");
        sb.Append('\n');
        sb.Append("# 2. To regenerate, set the environment variable below and re-run the gate;\n");
        sb.Append("#    it rewrites docs/language-reference.md from the freshly-composed schema.\n");
        sb.Append("#    Review the diff, then commit.\n");
        sb.Append("VOUCHFX_REGEN_LANGUAGE_REFERENCE=1 dotnet test tests/Vouchfx.Engine.Compilation.Tests \\\n");
        sb.Append("  --filter \"FullyQualifiedName~LanguageReferenceGoldenTests\"\n");
        sb.Append("```\n");
    }

    // ── Field rendering ────────────────────────────────────────────────────────

    private static void WriteFieldRow(StringBuilder sb, string name, JsonElement field, bool required)
    {
        var type = DescribeType(field);
        var description = TryGetString(field, "description") ?? string.Empty;

        sb.Append("| `").Append(name).Append("` | ")
          .Append(required ? "yes" : "no").Append(" | ")
          .Append(type).Append(" | ")
          .Append(EscapeTableCell(description)).Append(" |\n");
    }

    private static void WriteTypeFieldRow(StringBuilder sb, Field f)
    {
        sb.Append("| `").Append(f.Name).Append("` | ")
          .Append(f.Type).Append(" | ")
          .Append(EscapeTableCell(f.Description)).Append(" |\n");
    }

    // ── Schema navigation ──────────────────────────────────────────────────────

    private static JsonElement NavigateStepDefinition(JsonElement root)
    {
        if (!root.TryGetProperty("$defs", out var defs) || defs.ValueKind != JsonValueKind.Object)
            throw new InvalidOperationException("Composed schema is missing the '$defs' object.");

        if (!defs.TryGetProperty("step", out var step) || step.ValueKind != JsonValueKind.Object)
            throw new InvalidOperationException("Composed schema '$defs' is missing the 'step' definition.");

        return step;
    }

    private static List<StepType> ReadStepTypes(JsonElement step)
    {
        var result = new List<StepType>();

        if (!step.TryGetProperty("allOf", out var allOf) || allOf.ValueKind != JsonValueKind.Array)
            return result;

        foreach (var clause in allOf.EnumerateArray())
        {
            var typeId = TryReadConstTypeId(clause);
            if (typeId is null)
                continue;

            if (!clause.TryGetProperty("then", out var then) || then.ValueKind != JsonValueKind.Object)
                continue;

            var description = TryGetString(then, "description");
            var required = ReadRequiredSet(then);
            var fields = ReadFields(then);

            result.Add(new StepType(typeId, description, required, fields));
        }

        return result;
    }

    /// <summary>
    /// Reads the step-type discriminator from an <c>allOf</c> clause's
    /// <c>if.properties.type.const</c>.  Returns null when the clause is not a
    /// type-discriminator (so non-discriminator allOf clauses are skipped).
    /// </summary>
    private static string? TryReadConstTypeId(JsonElement clause)
    {
        if (!clause.TryGetProperty("if", out var ifClause) || ifClause.ValueKind != JsonValueKind.Object)
            return null;

        if (!ifClause.TryGetProperty("properties", out var props) || props.ValueKind != JsonValueKind.Object)
            return null;

        if (!props.TryGetProperty("type", out var typeProp) || typeProp.ValueKind != JsonValueKind.Object)
            return null;

        if (!typeProp.TryGetProperty("const", out var constValue) || constValue.ValueKind != JsonValueKind.String)
            return null;

        return constValue.GetString();
    }

    private static List<Field> ReadFields(JsonElement schemaObject)
    {
        var fields = new List<Field>();

        if (!schemaObject.TryGetProperty("properties", out var properties) ||
            properties.ValueKind != JsonValueKind.Object)
        {
            return fields;
        }

        foreach (var property in properties.EnumerateObject())
        {
            var name = property.Name;
            var type = DescribeType(property.Value);
            var description = TryGetString(property.Value, "description") ?? string.Empty;
            fields.Add(new Field(name, type, description));
        }

        return fields;
    }

    private static HashSet<string> ReadRequiredSet(JsonElement schemaObject)
    {
        var set = new HashSet<string>(StringComparer.Ordinal);

        if (schemaObject.TryGetProperty("required", out var required) &&
            required.ValueKind == JsonValueKind.Array)
        {
            foreach (var item in required.EnumerateArray())
            {
                if (item.ValueKind == JsonValueKind.String)
                {
                    var value = item.GetString();
                    if (!string.IsNullOrEmpty(value))
                        set.Add(value!);
                }
            }
        }

        return set;
    }

    // ── Type description ───────────────────────────────────────────────────────

    /// <summary>
    /// Renders a human-readable, backtick-wrapped JSON-Schema type for a field.
    /// Handles a scalar <c>type</c>, an array of types, a <c>oneOf</c> union
    /// (e.g. <c>timeout</c>: string | number), an <c>enum</c>, and the
    /// no-explicit-type case (e.g. <c>http.rest.body</c>, which accepts any JSON).
    /// </summary>
    private static string DescribeType(JsonElement field)
    {
        if (field.ValueKind != JsonValueKind.Object)
            return "`any`";

        // A oneOf union of typed alternatives (timeout: string | number).
        if (field.TryGetProperty("oneOf", out var oneOf) && oneOf.ValueKind == JsonValueKind.Array)
        {
            var alternatives = new List<string>();
            foreach (var alt in oneOf.EnumerateArray())
            {
                alternatives.AddRange(ReadScalarOrArrayTypes(alt));
            }

            if (alternatives.Count > 0)
            {
                return JoinAsBacktickedAlternatives(alternatives);
            }
        }

        var types = ReadScalarOrArrayTypes(field);
        if (types.Count > 0)
        {
            // A lone scalar type renders as its ORIGINAL single-code-span form
            // (`string`); a genuine multi-type union (httpPort's post-A1
            // "type": ["integer","string"], say) renders exactly like the
            // oneOf branch above and for the SAME measured reason (m1,
            // feat/close-remaining-surfaces second round) — see
            // JoinAsBacktickedAlternatives.
            return types.Count == 1 ? $"`{types[0]}`" : JoinAsBacktickedAlternatives(types);
        }

        // No declared type — the field accepts any JSON value (e.g. an inline body).
        return "`any`";
    }

    /// <summary>
    /// Renders 2+ JSON-Schema type names as one Markdown code span PER type,
    /// joined OUTSIDE every span by an escaped pipe — e.g.
    /// <c>`string` \| `number`</c> — never a pipe (escaped or not) INSIDE a
    /// single shared span.
    /// </summary>
    /// <remarks>
    /// Measured against the site's actual configured renderer (m1,
    /// feat/close-remaining-surfaces second round — the m1 in THIS round
    /// corrects the m1 in the PRECEDING round, whose own "description column
    /// dropped on the live site" claim was itself an unverified inference;
    /// see the commit message): fed all three forms through
    /// <c>markdown.markdown(...)</c> with this repo's exact pinned
    /// <c>mkdocs-material==9.7.7</c> and its <c>markdown_extensions</c> list
    /// (MkDocs always adds the <c>tables</c> builtin regardless of that
    /// list — confirmed from <c>mkdocs.config.defaults</c>'s own
    /// <c>builtins=['toc','tables','fenced_code']</c> — so the deployed
    /// renderer for docs/language-reference.md needs no extra extension to
    /// reproduce here). Results: a RAW pipe inside one span
    /// (<c>`string|number`</c>) does NOT split the table row in
    /// Python-Markdown's <c>tables</c> extension (only GFM breaks on that
    /// form); an ESCAPED pipe INSIDE one span (<c>`string\|number`</c> — this
    /// method's PREVIOUS fix) renders the LITERAL BACKSLASH character
    /// visibly, because code-span content is verbatim and backslash-escape
    /// processing does not reach inside it — making that form the WORST of
    /// the three on the deployed Pages site, worse than doing nothing; only
    /// the OUTSIDE-span form (used here, and already used by
    /// <see cref="DescribeType"/>'s oneOf-alternatives branch before this
    /// change) renders cleanly with no stray backslash on BOTH Python-Markdown
    /// and GFM.
    /// </remarks>
    private static string JoinAsBacktickedAlternatives(List<string> types) =>
        string.Join(" \\| ", types.Select(t => $"`{t}`"));

    /// <summary>
    /// Reads a <c>type</c> keyword that is either a single string or an array
    /// of strings, returning each type name as its OWN list entry — never
    /// pre-joined — so every caller renders through the ONE shared,
    /// measured-safe path (<see cref="JoinAsBacktickedAlternatives"/> for 2+
    /// entries, a single backtick span for exactly 1). Returns an empty list,
    /// never null, when no <c>type</c> is declared or none of its entries are
    /// non-empty strings.
    /// </summary>
    private static List<string> ReadScalarOrArrayTypes(JsonElement schemaObject)
    {
        var result = new List<string>();

        if (schemaObject.ValueKind != JsonValueKind.Object)
            return result;

        if (!schemaObject.TryGetProperty("type", out var typeNode))
            return result;

        if (typeNode.ValueKind == JsonValueKind.String)
        {
            var value = typeNode.GetString();
            if (!string.IsNullOrEmpty(value))
                result.Add(value!);

            return result;
        }

        if (typeNode.ValueKind == JsonValueKind.Array)
        {
            foreach (var item in typeNode.EnumerateArray())
            {
                if (item.ValueKind == JsonValueKind.String)
                {
                    var value = item.GetString();
                    if (!string.IsNullOrEmpty(value))
                        result.Add(value!);
                }
            }
        }

        return result;
    }

    // ── String helpers ─────────────────────────────────────────────────────────

    private static string? TryGetString(JsonElement obj, string propertyName)
    {
        if (obj.ValueKind == JsonValueKind.Object &&
            obj.TryGetProperty(propertyName, out var value) &&
            value.ValueKind == JsonValueKind.String)
        {
            return value.GetString();
        }

        return null;
    }

    /// <summary>
    /// Escapes a string for safe placement inside a single Markdown table cell:
    /// collapses any embedded newlines to spaces (a literal newline would break the
    /// table row) and escapes the pipe character (which would otherwise start a new
    /// column).
    /// </summary>
    private static string EscapeTableCell(string text)
    {
        if (string.IsNullOrEmpty(text))
            return string.Empty;

        var collapsed = text
            .Replace("\r\n", " ")
            .Replace('\n', ' ')
            .Replace('\r', ' ')
            .Replace("|", "\\|");

        // Collapse any runs of whitespace introduced by newline replacement so the
        // rendered cell is tidy and the bytes stay stable.
        return CollapseWhitespace(collapsed);
    }

    /// <summary>
    /// Escapes a string for inline prose (not a table cell): collapses newlines and
    /// runs of whitespace to a single space.
    /// </summary>
    private static string EscapeInline(string text)
    {
        if (string.IsNullOrEmpty(text))
            return string.Empty;

        var collapsed = text
            .Replace("\r\n", " ")
            .Replace('\n', ' ')
            .Replace('\r', ' ');

        return CollapseWhitespace(collapsed);
    }

    private static string CollapseWhitespace(string text)
    {
        var sb = new StringBuilder(text.Length);
        var lastWasSpace = false;

        foreach (var c in text)
        {
            if (c == ' ' || c == '\t')
            {
                if (!lastWasSpace)
                {
                    sb.Append(' ');
                    lastWasSpace = true;
                }
            }
            else
            {
                sb.Append(c);
                lastWasSpace = false;
            }
        }

        return sb.ToString().Trim();
    }

    /// <summary>
    /// Derives a GitHub-style Markdown anchor slug from a step-type id so the
    /// in-document index links resolve to the rendered <c>### `&lt;id&gt;`</c>
    /// heading.  GitHub lower-cases, strips the backticks, and replaces the dot
    /// with a hyphen-free join (dots are simply removed).
    /// </summary>
    private static string Anchor(string typeId)
    {
        var sb = new StringBuilder(typeId.Length);
        foreach (var c in typeId.ToLowerInvariant())
        {
            if (char.IsLetterOrDigit(c))
                sb.Append(c);
            else if (c == '-')
                sb.Append('-');
            // dots and other punctuation are dropped, matching GitHub's slugger.
        }

        return sb.ToString();
    }

    // ── Value records ──────────────────────────────────────────────────────────

    private sealed record StepType(
        string TypeId,
        string? Description,
        HashSet<string> Required,
        List<Field> Fields);

    private sealed record Field(string Name, string Type, string Description);
}
