<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Vouchfx.Steps.DbAssert.Dynamodb</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Sdk\Vouchfx.Sdk\Vouchfx.Sdk.csproj" />
    <ProjectReference Include="..\..\..\Engine\Vouchfx.Engine.Abstractions\Vouchfx.Engine.Abstractions.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AWSSDK.DynamoDBv2" />
  </ItemGroup>

</Project>
