// Platform.Steps.TraceExpect.Otlp — trace-expect.otlp step model (DSL §5.10, Phase C).
// Strongly-typed record; Dictionary<string,object> is explicitly prohibited (§13).
//
// This is the flagship distributed assertion (Phase C): it proves that a REAL trace with an
// expected span shape exists for the business transaction the scenario just drove — the
// causal-chain proof no single-service assertion (an HTTP 2xx, a DB row, a queue message) can
// give on its own. An earlier step (usually http.rest) injects a W3C `traceparent` header on
// its outbound request; the SUT's own OpenTelemetry SDK — running unmodified, no test-only
// shim — exports the spans it recorded for that request over OTLP/HTTP to the engine-hosted
// receiver (see Platform.Engine.Orchestration.HostResources.OtlpReceiver); this step scans the
// receiver's captured spans for one matching every declared criterion.
using Platform.Sdk;

namespace Platform.Steps.TraceExpect.Otlp;

/// <summary>
/// The criteria a captured OTLP span must satisfy for the <c>trace-expect.otlp</c> assertion
/// to pass (DSL §5.10).
/// </summary>
/// <remarks>
/// <para>
/// All declared criteria are conjunctive (logical AND): a captured span matches only when
/// every declared criterion is satisfied. <see cref="TraceId"/> is REQUIRED — an empty
/// <see cref="TraceId"/> is rejected by <see cref="TraceExpectOtlpProvider.Validate"/>, because
/// without it a declared <see cref="Service"/>/<see cref="SpanName"/>/<see cref="Attributes"/>
/// combination would accept ANY span the SUT ever exports that happens to match, from ANY
/// trace — not the specific transaction this scenario is asserting about. This is also what
/// makes the family's no-forged-match security posture (see the host-owned OTLP receiver's
/// remarks) an enforced guarantee rather than an authoring convention an author could
/// accidentally omit.
/// </para>
/// <para>
/// Every criterion supports <c>{placeholder}</c> substitution and <c>${secret:source/path}</c>
/// resolution, resolved at step-execution time inside the emitted helper's guarded region
/// (§17), exactly like every other Core provider's templated fields.
/// </para>
/// </remarks>
/// <param name="TraceId">
/// Required expected trace id — the transaction this assertion is tied to. The resolved value
/// is matched case-insensitively against a captured span's <c>TraceId</c> after extraction:
/// when the resolved string has the shape of a full W3C <c>traceparent</c> header
/// (<c>&lt;2-hex&gt;-&lt;32-hex&gt;-&lt;16-hex&gt;-&lt;2-hex&gt;</c>,
/// e.g. <c>00-4bf92f3577b34da6a3ce929d0e0e4736-00f067aa0ba902b7-01</c>), the 32-hex trace-id
/// segment is extracted and matched; otherwise the resolved value is matched verbatim (an
/// author who threads a bare 32-hex trace id forward — for example one generated by an earlier
/// <c>script.csharp</c> step — needs no traceparent parsing).
/// </param>
/// <param name="Service">
/// Optional expected exporting-resource service name (the span's resource-level
/// <c>service.name</c> attribute), matched by ordinal equality.
/// </param>
/// <param name="SpanName">
/// Optional expected span name (operation name, e.g. <c>"POST /orders"</c>), matched by
/// ordinal equality.
/// </param>
/// <param name="Attributes">
/// Optional map of expected span-attribute key to expected string value. When non-empty, every
/// named attribute must be present on the captured span with exactly the expected value
/// (ordinal key lookup and value comparison; a span may carry additional attributes not
/// mentioned here — a subset match, mirroring <c>metrics-assert.prometheus</c>'s label
/// matching). <see langword="null"/> or empty imposes no constraint.
/// </param>
public sealed record TraceMatch(
    string? TraceId,
    string? Service,
    string? SpanName,
    IReadOnlyDictionary<string, string>? Attributes);

/// <summary>
/// Strongly-typed model for the <c>trace-expect.otlp</c> step kind (DSL §5.10, Phase C).
/// </summary>
/// <remarks>
/// <para>
/// The step asserts that a host-owned ephemeral OTLP/HTTP receiver (named by
/// <see cref="Receiver"/>) has captured at least one span satisfying the declared
/// <see cref="Match"/> criteria. The receiver is itself a <em>host resource</em> this provider
/// contributes (via <c>IHostResourceContributor&lt;TraceExpectOtlpModel&gt;</c>); the engine
/// stands it up before any step runs and stages its base URL at
/// <c>svc::&lt;Receiver&gt;</c> and at the plain <c>Vars[&lt;Receiver&gt;]</c> key, ready to be
/// handed to the system under test's OpenTelemetry SDK configuration, e.g.
/// <c>OTEL_EXPORTER_OTLP_ENDPOINT: "{svc::traces}"</c> (Phase C mirrors S07-F-01a/b exactly).
/// </para>
/// <para>
/// This provider is a <c>verifyMode: RETRY</c> consumer (DSL §7) — RETRY is this family's
/// CANONICAL mode: a real OpenTelemetry SDK batches and exports spans on a periodic timer
/// (commonly ~5s), so the exported spans for a transaction the scenario just drove will almost
/// never have arrived by the time the very next step executes. The engine wraps a RETRY step
/// in a polling loop, so the emitted assertion is an IDEMPOTENT single scan of the captured-span
/// buffer. It writes <see cref="Platform.Engine.Abstractions.Verdict.Fail"/> when no captured
/// span matches THIS attempt and contains NO retry logic itself — the engine-owned RetryRunner
/// re-invokes the delegate and converts a sustained Fail to
/// <see cref="Platform.Engine.Abstractions.Verdict.Inconclusive"/> on timeout (§12.1).
/// </para>
/// </remarks>
/// <param name="Receiver">
/// The logical receiver name whose base URL is staged at <c>svc::&lt;Receiver&gt;</c> and whose
/// captured spans this step asserts against (read via
/// <c>ScriptGlobalVariables.Traces.GetCaptured(Receiver)</c>). Must not be empty.
/// </param>
/// <param name="Match">
/// The criteria a captured span must satisfy. <see cref="TraceMatch.TraceId"/> is required
/// (service/spanName/attributes are optional refinements layered on top of it); a match with
/// no trace id is rejected by validation.
/// </param>
public sealed record TraceExpectOtlpModel(string Receiver, TraceMatch Match) : IStepModel;
