#!/usr/bin/env python3
"""Build the vouchfx GitHub Pages site.

Copies the static landing page (site/) into the output directory, then renders
the repository's markdown design docs and delivery plan into styled HTML that
matches the landing page. The markdown files remain the single source of truth;
this generates their HTML on every run, so a CI deploy keeps the published docs
current with every push.

    python scripts/build_site.py [output_dir]   # default: _site

Requires: markdown, pygments  (pip install markdown pygments)
"""
from __future__ import annotations

import html
import os
import re
import shutil
import sys
from pathlib import Path

import markdown
from markdown.extensions.codehilite import CodeHiliteExtension
from markdown.extensions.toc import TocExtension
from pygments.formatters import HtmlFormatter

ROOT = Path(__file__).resolve().parent.parent
SITE = ROOT / "site"
OUT = Path(sys.argv[1]).resolve() if len(sys.argv) > 1 else ROOT / "_site"

# Markdown files to render, in sidebar order. (source path relative to ROOT, nav group, label)
DOCS: list[tuple[str, str, str]] = [
    ("docs/01_Technical_Architecture_and_Engineering_Blueprint.md", "Design docs", "01 · Architecture Blueprint"),
    ("docs/02_YAML_DSL_Specification_and_VSCode_Extension_Design.md", "Design docs", "02 · YAML DSL Specification"),
    ("docs/03_MVP_Project_Plan.md", "Design docs", "03 · MVP Project Plan"),
    ("plan/README.md", "Delivery plan", "Delivery Plan (overview)"),
    ("plan/roadmap.md", "Delivery plan", "Roadmap (Gantt)"),
    ("plan/sprint-01.md", "Delivery plan", "Sprint 01 — Foundations"),
    ("plan/sprint-01-implementation.md", "Delivery plan", "Sprint 01 — Implementation"),
    ("plan/sprint-02.md", "Delivery plan", "Sprint 02 — Close the risk (M1)"),
    ("plan/sprint-03.md", "Delivery plan", "Sprint 03 — Core compiler"),
    ("plan/sprint-04.md", "Delivery plan", "Sprint 04 — Provider pipeline"),
    ("plan/sprint-05.md", "Delivery plan", "Sprint 05 — Seed, secrets (M2)"),
    ("plan/sprint-06.md", "Delivery plan", "Sprint 06 — Async + RETRY"),
    ("plan/sprint-07.md", "Delivery plan", "Sprint 07 — Capture + runner"),
    ("plan/sprint-08.md", "Delivery plan", "Sprint 08 — Freeze & publish (M3)"),
    ("plan/sprint-09.md", "Delivery plan", "Sprint 09 — Editor & reports"),
    ("plan/sprint-10.md", "Delivery plan", "Sprint 10 — Contribution path"),
    ("plan/sprint-11.md", "Delivery plan", "Sprint 11 — Stabilisation (M4)"),
    ("plan/sprint-12.md", "Delivery plan", "Sprint 12 — Pilot & release (M5)"),
    ("README.md", "Project", "Project README"),
    ("CLAUDE.md", "Project", "Engineering guide (CLAUDE.md)"),
]

# Any additional markdown that is link-reachable but not in the sidebar.
EXTRA = ["docs/reviews/m1-exit-evidence.md"]

GA_BADGE = '\n---\n_Generated by [Claude Code](https://claude.ai/code)_'


def out_path(rel: str) -> Path:
    """Mirror the repo layout under OUT, with .html extension."""
    return OUT / (rel[:-3] + ".html")


def rel_root(target: Path) -> str:
    """Relative path from a generated file back to OUT root, e.g. '../'."""
    rp = os.path.relpath(OUT, target.parent)
    return "" if rp == "." else rp + "/"


def rewrite_links(body: str) -> str:
    """Turn relative .md links into .html; leave absolute URLs alone."""
    def repl(m: re.Match) -> str:
        href = m.group(1)
        if re.match(r"[a-z]+://", href) or href.startswith("#") or href.startswith("mailto:"):
            return m.group(0)
        new = re.sub(r"\.md(#|$)", r".html\1", href)
        return f'href="{new}"'

    return re.sub(r'href="([^"]+)"', repl, body)


def extract_mermaid(text: str) -> tuple[str, list[str]]:
    """Pull ```mermaid fenced blocks out before markdown processing."""
    blocks: list[str] = []

    def grab(m: re.Match) -> str:
        blocks.append(m.group(1))
        return f"\n@@MERMAID{len(blocks) - 1}@@\n"

    text = re.sub(r"```mermaid\n(.*?)```", grab, text, flags=re.DOTALL)
    return text, blocks


def sidebar(active_rel: str, root: str) -> str:
    groups: dict[str, list[str]] = {}
    for rel, group, label in DOCS:
        href = root + rel[:-3] + ".html"
        cls = ' class="active"' if rel == active_rel else ""
        groups.setdefault(group, []).append(f'<a href="{href}"{cls}>{html.escape(label)}</a>')
    parts = [f'<a href="{root}docs.html">← All documentation</a>']
    for group, links in groups.items():
        parts.append(f"<h4>{html.escape(group)}</h4>")
        parts.extend(links)
    return "\n".join(parts)


PAGE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<title>{title} · vouchfx docs</title>
<meta name="description" content="{desc}" />
<meta name="theme-color" content="#0b0f1a" />
<link rel="icon" href="{root}favicon.svg" type="image/svg+xml" />
<link rel="stylesheet" href="{root}styles.css" />
<link rel="stylesheet" href="{root}docs.css" />
<link rel="stylesheet" href="{root}pygments.css" />
</head>
<body>
<header class="nav">
  <div class="nav__inner">
    <a class="brand" href="{root}index.html" aria-label="vouchfx home">
      <span class="brand__mark" aria-hidden="true"></span>
      <span class="brand__name">vouchfx</span>
    </a>
    <nav class="nav__links" aria-label="Primary">
      <a href="{root}index.html">Home</a>
      <a href="{root}docs.html">Docs</a>
      <a href="{root}index.html#architecture">Architecture</a>
      <a href="{root}index.html#roadmap">Roadmap</a>
    </nav>
    <a class="btn btn--ghost nav__gh" href="https://github.com/tomas-rampas/vouchfx" target="_blank" rel="noopener noreferrer">GitHub</a>
  </div>
</header>
<div class="doc-shell">
  <aside class="doc-side">{sidebar}</aside>
  <main class="doc-main">
    <div class="doc-breadcrumb"><a href="{root}docs.html">Documentation</a> / {crumb}</div>
    <article class="prose">{body}</article>
  </main>
  <nav class="doc-toc"><h4>On this page</h4>{toc}</nav>
</div>
{mermaid_script}
</body>
</html>
"""


def render_markdown(rel: str, label: str) -> None:
    src = ROOT / rel
    text = src.read_text(encoding="utf-8")
    text, mermaid = extract_mermaid(text)

    md = markdown.Markdown(
        extensions=[
            "extra",
            "sane_lists",
            "admonition",
            TocExtension(permalink=True, permalink_class="headerlink", permalink_title="", baselevel=2),
            CodeHiliteExtension(css_class="codehilite", guess_lang=False),
        ]
    )
    body = md.convert(text)
    body = rewrite_links(body)

    # Re-insert mermaid blocks as divs.
    for i, block in enumerate(mermaid):
        body = body.replace(f"<p>@@MERMAID{i}@@</p>", f'<div class="mermaid">{html.escape(block)}</div>')
        body = body.replace(f"@@MERMAID{i}@@", f'<div class="mermaid">{html.escape(block)}</div>')

    toc = getattr(md, "toc", "") or ""
    has_mermaid = bool(mermaid)
    mermaid_script = (
        '<script type="module">import mermaid from "https://cdn.jsdelivr.net/npm/mermaid@11/dist/mermaid.esm.min.mjs";'
        'mermaid.initialize({startOnLoad:true,theme:"dark"});</script>'
        if has_mermaid
        else ""
    )

    dst = out_path(rel)
    dst.parent.mkdir(parents=True, exist_ok=True)
    root = rel_root(dst)
    desc = f"vouchfx documentation — {label}"
    dst.write_text(
        PAGE.format(
            title=html.escape(label),
            desc=html.escape(desc),
            root=root,
            sidebar=sidebar(rel, root),
            crumb=html.escape(label),
            body=body,
            toc=toc,
            mermaid_script=mermaid_script,
        ),
        encoding="utf-8",
    )
    print(f"  rendered {rel} -> {dst.relative_to(OUT)}")


PORTAL = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<title>Documentation · vouchfx</title>
<meta name="description" content="vouchfx documentation — the architecture blueprint, the YAML DSL specification, the MVP project plan, and the milestone-driven delivery plan." />
<meta name="theme-color" content="#0b0f1a" />
<link rel="icon" href="favicon.svg" type="image/svg+xml" />
<link rel="stylesheet" href="styles.css" />
<link rel="stylesheet" href="docs.css" />
</head>
<body>
<header class="nav">
  <div class="nav__inner">
    <a class="brand" href="index.html" aria-label="vouchfx home">
      <span class="brand__mark" aria-hidden="true"></span>
      <span class="brand__name">vouchfx</span>
    </a>
    <nav class="nav__links" aria-label="Primary">
      <a href="index.html">Home</a>
      <a href="index.html#architecture">Architecture</a>
      <a href="index.html#dsl">The DSL</a>
      <a href="index.html#roadmap">Roadmap</a>
    </nav>
    <a class="btn btn--ghost nav__gh" href="https://github.com/tomas-rampas/vouchfx" target="_blank" rel="noopener noreferrer">GitHub</a>
  </div>
</header>
<div class="container portal">
  <div class="portal__head">
    <p class="eyebrow">Documentation</p>
    <h1 class="section__title">The design is the source of truth.</h1>
    <p class="section__lede">vouchfx is a fully-specified system. These pages are rendered straight from the
      repository's markdown on every push, so they never drift from the code.</p>
  </div>

  <section class="portal__group">
    <h2>Design docs</h2>
    <p>How the system is built, and the language it runs.</p>
    <div class="doc-cards">
      <a class="doc-card" href="docs/01_Technical_Architecture_and_Engineering_Blueprint.html">
        <span class="doc-card__k">01</span><h3>Technical Architecture &amp; Engineering Blueprint</h3>
        <p>The single source of truth: the five layers, Aspire/Testcontainers, the Roslyn compiler and memory model, security, the verdict taxonomy, provider architecture, reporting and secrets.</p>
      </a>
      <a class="doc-card" href="docs/02_YAML_DSL_Specification_and_VSCode_Extension_Design.html">
        <span class="doc-card__k">02</span><h3>YAML DSL Specification &amp; VSCode Extension</h3>
        <p>The <code>.e2e.yaml</code> grammar — document structure, step families, capture/placeholder syntax, verification modes, the JSON Schema contract, and the editor tooling.</p>
      </a>
      <a class="doc-card" href="docs/03_MVP_Project_Plan.html">
        <span class="doc-card__k">03</span><h3>MVP Project Plan</h3>
        <p>Scope, the seven workstreams, phasing, and what is in the MVP versus later.</p>
      </a>
    </div>
  </section>

  <section class="portal__group">
    <h2>Delivery plan</h2>
    <p>The MVP decomposed into five milestones, twelve sprints, and trackable tasks.</p>
    <div class="doc-cards" style="margin-bottom:16px">
      <a class="doc-card" href="plan/README.html">
        <span class="doc-card__k">PLAN</span><h3>Delivery Plan — overview</h3>
        <p>Conventions, capacity, milestone gates, the workstreams, and the hard-invariant review checklist.</p>
      </a>
      <a class="doc-card" href="plan/roadmap.html">
        <span class="doc-card__k">GANTT</span><h3>Delivery Roadmap</h3>
        <p>The milestone &amp; sprint timeline as a Mermaid Gantt overview.</p>
      </a>
    </div>
    <div class="doc-list">{sprint_list}</div>
  </section>

  <section class="portal__group">
    <h2>Project</h2>
    <p>Repository orientation and the operating rules for contributors.</p>
    <div class="doc-cards">
      <a class="doc-card" href="README.html"><span class="doc-card__k">README</span><h3>Project README</h3><p>What vouchfx is, how it works, building &amp; testing, and the repository layout.</p></a>
      <a class="doc-card" href="CLAUDE.html"><span class="doc-card__k">GUIDE</span><h3>Engineering guide</h3><p>The hard invariants and operating rules every contributor — human or agent — must honour.</p></a>
    </div>
  </section>
</div>

<footer class="footer">
  <div class="container footer__inner">
    <div class="footer__brand">
      <span class="brand__mark" aria-hidden="true"></span>
      <div><strong>vouchfx</strong><p>End-to-end integration testing for distributed systems, authored in YAML.</p></div>
    </div>
    <div class="footer__links">
      <a href="index.html">Home</a>
      <a href="https://github.com/tomas-rampas/vouchfx" target="_blank" rel="noopener noreferrer">Repository</a>
      <a href="https://github.com/tomas-rampas/vouchfx/blob/main/LICENSE" target="_blank" rel="noopener noreferrer">Licence (Apache-2.0)</a>
    </div>
  </div>
</footer>
</body>
</html>
"""


def build_portal() -> None:
    sprints = [d for d in DOCS if d[0].startswith("plan/sprint-")]
    items = []
    for rel, _group, label in sprints:
        href = rel[:-3] + ".html"
        num = re.search(r"sprint-(\d+)", rel)
        tag = f"S{num.group(1)}" if num else "·"
        short = label.split("—", 1)[-1].strip() if "—" in label else label
        items.append(f'<a href="{href}"><b>{tag}</b><span>{html.escape(short)}</span></a>')
    (OUT / "docs.html").write_text(PORTAL.format(sprint_list="\n".join(items)), encoding="utf-8")
    print("  built docs.html portal")


def main() -> None:
    if OUT.exists():
        shutil.rmtree(OUT)
    shutil.copytree(SITE, OUT)
    print(f"copied {SITE.relative_to(ROOT)}/ -> {OUT.name}/")

    # Pygments stylesheet (dark) for fenced code blocks.
    (OUT / "pygments.css").write_text(
        HtmlFormatter(style="monokai").get_style_defs(".codehilite") + "\n.codehilite{background:transparent}",
        encoding="utf-8",
    )

    for rel, _group, label in DOCS:
        render_markdown(rel, label)
    for rel in EXTRA:
        if (ROOT / rel).exists():
            render_markdown(rel, Path(rel).stem)

    build_portal()
    print(f"done -> {OUT}")


if __name__ == "__main__":
    main()
